export const SUBJECT_CHANGE = 'SUBJECT_CHANGE';
export const INITIAL_STAGE_CHANGE = 'INITIAL_STAGE_CHANGE'
export const ONGOING_STAGE_CHANGE = 'ONGOING_STAGE_CHANGE'
export const COMPLETE_STAGE_CHANGE = 'COMPLETE_STAGE_CHANGE'
export const WORKITEM_CHAGNE = 'WORKITEM_CHAGNE'
export const VIEW_ID_CHANGE = 'VIEW_ID_CHANGE'
